export const data = [
    { question:"What is the name of the city ?",
        option1 :"Bangalore",
        option2:"Mangalore",
        option3:"Kolkata",
        option4:"Gulbarga",
        ans:1,
    },
    { question:"What is the name of the Country ?",
        option1 :"India",
        option2:"Africa",
        option3:"America",
        option4:"Russia",
        ans:1,
    },
    { question:"What is Your name ?",
        option1 :"Rahul",
        option2:"Kavya",
        option3:"Yashwaswini",
        option4:"Ranjith",
        ans:4,
    },
     { question:"What is Your wife name ?",
        option1 :"Rahul",
        option2:"Kavya",
        option3:"Yashwaswini",
        option4:"Ranjith",
        ans:3,
    },
     { question:"What is Your x name ?",
        option1 :"Rahul",
        option2:"Kavya",
        option3:"Yashwaswini",
        option4:"Ahana",
        ans:4,
    }
]