export const data =  [
  {
    question: "Which planet is known as the Red Planet?",
    option1: "Earth",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Venus",
    ans: 2,
  },
  {
    question: "What is the capital of India?",
    option1: "Mumbai",
    option2: "Chennai",
    option3: "New Delhi",
    option4: "Hyderabad",
    ans: 3,
  },
  {
    question: "Which language is used for styling web pages?",
    option1: "HTML",
    option2: "JQuery",
    option3: "CSS",
    option4: "XML",
    ans: 3,
  },
  {
    question: "Which company developed React.js?",
    option1: "Google",
    option2: "Facebook",
    option3: "Microsoft",
    option4: "Amazon",
    ans: 2,
  },
  {
    question: "Which data structure uses FIFO (First In First Out)?",
    option1: "Stack",
    option2: "Queue",
    option3: "Tree",
    option4: "Graph",
    ans: 2,
  },
  {
    question: "Which keyword is used to declare a variable in JavaScript?",
    option1: "var",
    option2: "int",
    option3: "string",
    option4: "define",
    ans: 1,
  },
  {
    question: "Which HTML tag is used to create a hyperlink?",
    option1: "<link>",
    option2: "<a>",
    option3: "<href>",
    option4: "<url>",
    ans: 2,
  },
  {
    question: "Which is the largest ocean in the world?",
    option1: "Atlantic Ocean",
    option2: "Indian Ocean",
    option3: "Pacific Ocean",
    option4: "Arctic Ocean",
    ans: 3,
  },
  {
    question: "Which method is used to add an element at the end of an array in JavaScript?",
    option1: "push()",
    option2: "pop()",
    option3: "shift()",
    option4: "unshift()",
    ans: 1,
  },
  {
    question: "Which country is famous for the Great Wall?",
    option1: "India",
    option2: "China",
    option3: "Japan",
    option4: "Korea",
    ans: 2,
  }
];